import type { Restaurant, Category, Order } from '@/types'

export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 1,
    name: 'La Bella Italia',
    slug: 'la-bella-italia',
    description: 'Authentique cuisine italienne préparée avec passion. Pizzas au feu de bois, pâtes fraîches maison.',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=200&q=80',
    cuisine: ['Italien', 'Pizza', 'Pâtes'],
    rating: 4.8,
    review_count: 342,
    delivery_time: 25,
    delivery_fee: 2.5,
    min_order: 12,
    is_open: true,
    featured: true,
    promo: '-20% sur les pizzas',
    address: { street: '12 rue de la Paix', city: 'Paris', zip: '75001' },
  },
  {
    id: 2,
    name: 'Tokyo Garden',
    slug: 'tokyo-garden',
    description: 'Sushis, ramens et spécialités japonaises préparées par nos chefs expérimentés.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=200&q=80',
    cuisine: ['Japonais', 'Sushi', 'Ramen'],
    rating: 4.9,
    review_count: 521,
    delivery_time: 35,
    delivery_fee: 3,
    min_order: 18,
    is_open: true,
    featured: true,
    address: { street: '45 avenue Montaigne', city: 'Paris', zip: '75008' },
  },
  {
    id: 3,
    name: 'Le Burger Gourmet',
    slug: 'le-burger-gourmet',
    description: 'Burgers artisanaux avec des viandes sélectionnées, frites fraîches et sauces maison.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=200&q=80',
    cuisine: ['Burger', 'Américain', 'Fast Food'],
    rating: 4.5,
    review_count: 189,
    delivery_time: 20,
    delivery_fee: 1.99,
    min_order: 10,
    is_open: true,
    promo: 'Livraison gratuite',
    address: { street: '8 rue du Faubourg', city: 'Paris', zip: '75009' },
  },
  {
    id: 4,
    name: 'Épices du Monde',
    slug: 'epices-du-monde',
    description: 'Voyage culinaire à travers les saveurs indiennes et thaïlandaises.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=200&q=80',
    cuisine: ['Indien', 'Thaï', 'Épicé'],
    rating: 4.6,
    review_count: 267,
    delivery_time: 40,
    delivery_fee: 2,
    min_order: 14,
    is_open: false,
    address: { street: '22 rue de la République', city: 'Lyon', zip: '69001' },
  },
  {
    id: 5,
    name: 'Crêperie Bretonne',
    slug: 'creperie-bretonne',
    description: 'Crêpes et galettes tradition­nelles au sarrasin, faites à la main.',
    image: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=200&q=80',
    cuisine: ['Français', 'Crêpes', 'Brunch'],
    rating: 4.7,
    review_count: 134,
    delivery_time: 22,
    delivery_fee: 1.5,
    min_order: 8,
    is_open: true,
    address: { street: '3 place du Marché', city: 'Rennes', zip: '35000' },
  },
  {
    id: 6,
    name: 'Poke Paradise',
    slug: 'poke-paradise',
    description: 'Poke bowls frais et healthy avec des ingrédients de qualité premium.',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80',
    logo: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=200&q=80',
    cuisine: ['Hawaïen', 'Healthy', 'Poke'],
    rating: 4.4,
    review_count: 88,
    delivery_time: 18,
    delivery_fee: 2.5,
    min_order: 12,
    is_open: true,
    address: { street: '67 boulevard Haussmann', city: 'Paris', zip: '75009' },
  },
]

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 1,
    name: 'Pizzas',
    items: [
      {
        id: 101,
        name: 'Margherita',
        description: 'Sauce tomate fraîche, mozzarella di bufala, basilic frais',
        price: 13.5,
        image: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=400&q=80',
        category_id: 1,
        tags: ['Végétarien'],
        is_available: true,
        extras: [
          { id: 1, name: 'Mozzarella supplémentaire', price: 2 },
          { id: 2, name: 'Champignons', price: 1.5 },
        ],
      },
      {
        id: 102,
        name: 'Quattro Stagioni',
        description: 'Jambon, champignons, poivrons, olives noires, mozzarella',
        price: 16.5,
        image: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=400&q=80',
        category_id: 1,
        is_available: true,
        extras: [{ id: 3, name: 'Anchois', price: 1.5 }],
      },
      {
        id: 103,
        name: 'Truffe & Parmesan',
        description: 'Crème de truffe, copeaux de parmesan 24 mois, roquette',
        price: 22,
        image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=400&q=80',
        category_id: 1,
        tags: ['Premium'],
        is_available: true,
      },
    ],
  },
  {
    id: 2,
    name: 'Pâtes',
    items: [
      {
        id: 201,
        name: 'Carbonara',
        description: 'Spaghetti, guanciale, œuf, pecorino romano, poivre noir',
        price: 14,
        image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&q=80',
        category_id: 2,
        is_available: true,
      },
      {
        id: 202,
        name: 'Pesto Genovese',
        description: 'Trofie au basilic, pignons de pin, parmesan, tomates cerises',
        price: 13.5,
        image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&q=80',
        category_id: 2,
        tags: ['Végétarien'],
        is_available: true,
      },
    ],
  },
  {
    id: 3,
    name: 'Desserts',
    items: [
      {
        id: 301,
        name: 'Tiramisu Maison',
        description: 'Recette traditionnelle, mascarpone, café, biscuits à la cuillère',
        price: 7.5,
        image: 'https://images.unsplash.com/photo-1568051243851-f9b136146e97?w=400&q=80',
        category_id: 3,
        is_available: true,
      },
      {
        id: 302,
        name: 'Panna Cotta',
        description: 'Vanille de Madagascar, coulis de fruits rouges',
        price: 6.5,
        image: 'https://images.unsplash.com/photo-1488477181228-c84a438e7e76?w=400&q=80',
        category_id: 3,
        is_available: true,
      },
    ],
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 1,
    reference: 'SE-2024-001',
    status: 'delivering' as never,
    restaurant: MOCK_RESTAURANTS[0],
    items: [],
    delivery_address: { street: '15 rue Victor Hugo', city: 'Paris', zip: '75016' },
    subtotal: 42.5,
    delivery_fee: 2.5,
    discount: 0,
    total: 45,
    payment_method: 'card',
    estimated_delivery: '18:45',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    driver: {
      id: 1,
      name: 'Marc Dupont',
      phone: '+33 6 12 34 56 78',
      vehicle: 'Vélo électrique',
      rating: 4.9,
    },
  },
]

export const CUISINES = [
  { name: 'Tout', icon: '🍽️' },
  { name: 'Pizza', icon: '🍕' },
  { name: 'Sushi', icon: '🍱' },
  { name: 'Burger', icon: '🍔' },
  { name: 'Asiatique', icon: '🥢' },
  { name: 'Indien', icon: '🫕' },
  { name: 'Healthy', icon: '🥗' },
  { name: 'Français', icon: '🥐' },
  { name: 'Dessert', icon: '🍰' },
]
